//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingProject2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class accmgrcom
    {
        public string accmgr_id { get; set; }
        public string type { get; set; }
        public byte seq { get; set; }
        public decimal fromamt { get; set; }
        public decimal toamt { get; set; }
        public decimal fromday { get; set; }
        public decimal today { get; set; }
        public decimal compec { get; set; }
    }
}
