//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingProject2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ar
    {
        public string custcode { get; set; }
        public string doc_type { get; set; }
        public string doc_no { get; set; }
        public int seq { get; set; }
        public System.DateTime doc_date { get; set; }
        public System.DateTime due_date { get; set; }
        public string refno { get; set; }
        public string refno2 { get; set; }
        public string refno3 { get; set; }
        public string desp { get; set; }
        public string desp2 { get; set; }
        public string desp3 { get; set; }
        public string desp4 { get; set; }
        public string remark1 { get; set; }
        public string remark2 { get; set; }
        public string cheque_no { get; set; }
        public System.DateTime chqrc_date { get; set; }
        public System.DateTime koff_date { get; set; }
        public string curr_code { get; set; }
        public decimal fx_rate { get; set; }
        public decimal fx_gainloss { get; set; }
        public decimal amount { get; set; }
        public decimal paid { get; set; }
        public decimal local_amount { get; set; }
        public decimal local_paid { get; set; }
        public decimal taxable { get; set; }
        public decimal tax { get; set; }
        public decimal fx_taxable { get; set; }
        public decimal fx_tax { get; set; }
        public bool knockoff { get; set; }
        public string accmgr_id { get; set; }
        public string projcode { get; set; }
        public string deptcode { get; set; }
        public string billtype { get; set; }
        public string spcode { get; set; }
        public string source { get; set; }
        public System.DateTime taxdate { get; set; }
        public System.DateTime taxdate_bt { get; set; }
        public string lkdoc_type { get; set; }
        public string lkdoc_no { get; set; }
        public int lkseq { get; set; }
    }
}
