//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingProject2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class buyer
    {
        public string buyer_id { get; set; }
        public string buyer_name { get; set; }
        public string buyer_name2 { get; set; }
        public string addr1 { get; set; }
        public string addr2 { get; set; }
        public string postcode { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string country { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public string taxno { get; set; }
        public string accno { get; set; }
        public string nric { get; set; }
        public string gender { get; set; }
        public string race { get; set; }
        public string job { get; set; }
        public System.DateTime dob { get; set; }
        public System.DateTime regdate { get; set; }
        public System.DateTime expdate { get; set; }
        public bool member { get; set; }
        public bool editname { get; set; }
        public bool inactive { get; set; }
    }
}
