//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingProject2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cb
    {
        public string accno { get; set; }
        public string doc_type { get; set; }
        public string doc_no { get; set; }
        public int seq { get; set; }
        public System.DateTime doc_date { get; set; }
        public string refno { get; set; }
        public string refno2 { get; set; }
        public string refno3 { get; set; }
        public string desp { get; set; }
        public string desp2 { get; set; }
        public string desp3 { get; set; }
        public string desp4 { get; set; }
        public string remark1 { get; set; }
        public string remark2 { get; set; }
        public decimal amount { get; set; }
        public decimal debit { get; set; }
        public decimal credit { get; set; }
        public decimal fx_amount { get; set; }
        public decimal fx_debit { get; set; }
        public decimal fx_credit { get; set; }
        public decimal fx_rate { get; set; }
        public string curr_code { get; set; }
        public string cheque_no { get; set; }
        public System.DateTime recon_date { get; set; }
        public bool recon_flag { get; set; }
        public string source { get; set; }
    }
}
