//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingProject2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class counter
    {
        public string counter_no { get; set; }
        public string counter_desp { get; set; }
        public decimal curr_no { get; set; }
        public int doc_set { get; set; }
        public decimal startamt { get; set; }
        public string pcname { get; set; }
        public string location { get; set; }
        public string rptfile { get; set; }
        public string rptprinter { get; set; }
        public string rptversion { get; set; }
        public string invfile { get; set; }
        public string invprinter { get; set; }
        public string invversion { get; set; }
        public bool printopt { get; set; }
        public bool printpreview { get; set; }
        public bool drawer { get; set; }
        public byte drawer_linkto { get; set; }
        public byte drawer_port { get; set; }
        public string drawer_cmd { get; set; }
        public string drawer_printer { get; set; }
        public bool pole { get; set; }
        public byte pole_port { get; set; }
        public string pole_cmd { get; set; }
        public bool printsalessum { get; set; }
        public byte printcopy_card { get; set; }
        public bool inactive { get; set; }
    }
}
