//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingProject2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class countertsdet
    {
        public string counter_no { get; set; }
        public decimal tsno { get; set; }
        public string cashier_id { get; set; }
        public string supervisor_id { get; set; }
        public System.DateTime tsdate { get; set; }
        public string reason { get; set; }
        public decimal amount { get; set; }
    }
}
