//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingProject2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class currency
    {
        public string curr_code { get; set; }
        public string desp { get; set; }
        public string curr_sym { get; set; }
        public string curr_word { get; set; }
        public string countrycode { get; set; }
        public bool inactive { get; set; }
    }
}
