//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingProject2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class defdocno
    {
        public string doc_type { get; set; }
        public int doc_set { get; set; }
        public string desp { get; set; }
        public string prefix { get; set; }
        public string suffix { get; set; }
        public decimal curr_no { get; set; }
        public byte doc_width { get; set; }
        public bool auto { get; set; }
        public string grpdesp { get; set; }
        public string doc_desp { get; set; }
        public bool approval { get; set; }
        public string approvalusrgrp { get; set; }
        public bool rndadj { get; set; }
        public string rndformula { get; set; }
        public bool prodremark { get; set; }
        public bool followdesp { get; set; }
        public byte seq { get; set; }
    }
}
