//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingProject2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class defoption
    {
        public string defcode { get; set; }
        public string desp { get; set; }
        public string ftype { get; set; }
        public string fchar { get; set; }
        public decimal fnum { get; set; }
        public System.DateTime fdate { get; set; }
        public bool fbit { get; set; }
        public string ftext { get; set; }
    }
}
