//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingProject2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class defprofile
    {
        public byte id { get; set; }
        public string cname { get; set; }
        public string addr1 { get; set; }
        public string addr2 { get; set; }
        public string addr3 { get; set; }
        public string addr4 { get; set; }
        public string phone1 { get; set; }
        public string phone2 { get; set; }
        public string fax { get; set; }
        public string regno { get; set; }
        public string taxno { get; set; }
        public string email { get; set; }
        public string website { get; set; }
        public System.DateTime fyfromdate { get; set; }
        public System.DateTime fytodate { get; set; }
        public System.DateTime fystartdate { get; set; }
        public string curr_code { get; set; }
        public string gstformat { get; set; }
        public string logofile { get; set; }
        public string logo { get; set; }
        public System.DateTime sysdbdate { get; set; }
        public string sysdbver { get; set; }
    }
}
