//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingProject2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class defrptfile
    {
        public string formname { get; set; }
        public int rptid { get; set; }
        public string rptdesp { get; set; }
        public string rptfile { get; set; }
        public bool rptdefault { get; set; }
        public string rptprinter { get; set; }
        public string rptversion { get; set; }
        public int seq { get; set; }
        public string wm_file { get; set; }
        public byte wm_type { get; set; }
        public decimal wm_tpr { get; set; }
        public decimal wm_height { get; set; }
        public decimal wm_width { get; set; }
        public string user_id { get; set; }
        public string param1 { get; set; }
        public string init_table { get; set; }
        public bool inactive { get; set; }
    }
}
