//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingProject2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class defrefno
    {
        public string ref_type { get; set; }
        public int ref_set { get; set; }
        public string desp { get; set; }
        public string prefix { get; set; }
        public string suffix { get; set; }
        public decimal curr_no { get; set; }
        public byte doc_width { get; set; }
        public bool auto { get; set; }
        public string grpdesp { get; set; }
        public byte seq { get; set; }
    }
}
