//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingProject2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class defxl
    {
        public string xid { get; set; }
        public int seq { get; set; }
        public string title1 { get; set; }
        public string title2 { get; set; }
        public string title3 { get; set; }
        public string title4 { get; set; }
        public byte titlesize1 { get; set; }
        public byte titlesize2 { get; set; }
        public byte titlesize3 { get; set; }
        public byte titlesize4 { get; set; }
        public bool titlebold1 { get; set; }
        public bool titlebold2 { get; set; }
        public bool titlebold3 { get; set; }
        public bool titlebold4 { get; set; }
        public bool titleitalic1 { get; set; }
        public bool titleitalic2 { get; set; }
        public bool titleitalic3 { get; set; }
        public bool titleitalic4 { get; set; }
        public string colfld { get; set; }
        public string coltext { get; set; }
        public string colwidth { get; set; }
        public string colsum { get; set; }
        public string colalign { get; set; }
        public byte colend { get; set; }
        public string groupfld { get; set; }
        public string grouptext { get; set; }
        public bool groupbold { get; set; }
        public bool groupitalic { get; set; }
        public bool groupline { get; set; }
        public string sqlcmd1 { get; set; }
        public string sqlcmd2 { get; set; }
        public string sqlvfp { get; set; }
        public byte papersize { get; set; }
        public byte orient { get; set; }
        public string xfontname { get; set; }
        public byte xbodysize { get; set; }
        public byte xbodyheight { get; set; }
    }
}
