//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingProject2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class extdoc
    {
        public string ext_type { get; set; }
        public string code { get; set; }
        public string doc_type { get; set; }
        public string doc_no { get; set; }
        public int doc_seq { get; set; }
        public string desp { get; set; }
        public string doc_file { get; set; }
    }
}
