//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingProject2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class facategory
    {
        public string facate { get; set; }
        public string catedesp { get; set; }
        public string depr_method { get; set; }
        public decimal depr_rate { get; set; }
        public decimal depr_life { get; set; }
        public string prefix { get; set; }
        public string suffix { get; set; }
        public decimal curr_no { get; set; }
        public byte no_width { get; set; }
        public bool auto { get; set; }
    }
}
