//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingProject2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class fasset
    {
        public string fano { get; set; }
        public string fadesp { get; set; }
        public string fadesp2 { get; set; }
        public string facate { get; set; }
        public string vendorno { get; set; }
        public string barcode { get; set; }
        public string modelno { get; set; }
        public string serialno { get; set; }
        public System.DateTime warranty { get; set; }
        public System.DateTime purc_date { get; set; }
        public decimal purc_price { get; set; }
        public decimal scrapvalue { get; set; }
        public System.DateTime disp_date { get; set; }
        public decimal disp_value { get; set; }
        public System.DateTime depr_date { get; set; }
        public string accno { get; set; }
        public string depr_accno { get; set; }
        public string projcode { get; set; }
        public string deptcode { get; set; }
        public string branch { get; set; }
        public string empno { get; set; }
        public string status { get; set; }
        public string remarks { get; set; }
    }
}
