//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingProject2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class fatran
    {
        public string fano { get; set; }
        public System.DateTime tsdate { get; set; }
        public string desp { get; set; }
        public decimal depr_rate { get; set; }
        public decimal amount { get; set; }
        public string doc_type { get; set; }
        public string doc_no { get; set; }
        public int seq { get; set; }
        public bool postgl { get; set; }
    }
}
