//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingProject2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class glconsodet
    {
        public int mkey { get; set; }
        public string accno { get; set; }
        public decimal col_aval { get; set; }
        public decimal col_apct { get; set; }
        public decimal col_fval { get; set; }
        public decimal col_fpct { get; set; }
        public decimal col_bf { get; set; }
        public decimal col_adj { get; set; }
        public decimal col_cf { get; set; }
    }
}
