//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingProject2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class glconso
    {
        public int mkey { get; set; }
        public string projcode { get; set; }
        public string deptcode { get; set; }
        public string coldesp1 { get; set; }
        public string coldesp2 { get; set; }
        public System.DateTime coldate { get; set; }
        public byte rptcol { get; set; }
    }
}
