//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingProject2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class gldata
    {
        public gldata()
        {
            accdesp2 = "";
            contact = "";
            taxno = "";
            regno = String.Empty;
            subclassify = "";
            bankaccno = "";
            taxcode = "";

        }
        [DisplayName("A/C No")]
        public string accno { get; set; }

        [DisplayName("A/C Description")]
        public string accdesp { get; set; }
        [DisplayFormat(ConvertEmptyStringToNull = false)]
        [DisplayName("A/C 2nd Description")]
        public string accdesp2 { get; set; }

        [DisplayName("A/C Group")]
        public string grp_code { get; set; }
        [DisplayName("Currency")]
        public string curr_code { get; set; }
        [DisplayName("Group To A/C")]
        public string ctrlaccno { get; set; }
        [DisplayName("Classify")]
        public string classify { get; set; }
        [DisplayFormat(ConvertEmptyStringToNull = false)]
        public string subclassify { get; set; }
        [DisplayFormat(ConvertEmptyStringToNull = false)]
        public string bankaccno { get; set; }
        [DisplayFormat(ConvertEmptyStringToNull = false)]
        public string contact { get; set; }
        [DisplayFormat(ConvertEmptyStringToNull = false)]
        public string regno { get; set; }

       [DisplayFormat(ConvertEmptyStringToNull = false)]
        public string taxno { get; set; }

        public short terms { get; set; }
        [DisplayFormat(ConvertEmptyStringToNull = false)]
        public string taxcode { get; set; }

        public decimal disposal { get; set; }
        public byte cashflow { get; set; }
        public bool check_acc1 { get; set; }
        public bool check_acc2 { get; set; }
        public bool check_acc3 { get; set; }

        public List<SelectListItem> GlgroupItems { get; set; }
    }
}
