//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingProject2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class glgrp
    {
        public string grp_code { get; set; }
        public string grp_desp { get; set; }
        public byte grp_seq { get; set; }
        public decimal grp_sign { get; set; }
        public byte grp_type { get; set; }
        public string grp_section { get; set; }
        public byte grp_order1 { get; set; }
        public byte grp_order2 { get; set; }
        public string grp_order1_h { get; set; }
        public string grp_order1_f { get; set; }
        public string grp_order2_h { get; set; }
        public string grp_order2_f { get; set; }
        public bool grp_netca { get; set; }
        public bool grp_net { get; set; }
        public string grp_netca_desp { get; set; }
        public string grp_net_desp { get; set; }
        //public virtual ICollection<gldata> gldata { get; set; }
    }
}
