//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingProject2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gloff
    {
        public string accno { get; set; }
        public string doc_type { get; set; }
        public string doc_no { get; set; }
        public int seq { get; set; }
        public System.DateTime doc_date { get; set; }
        public string pkdoc_type { get; set; }
        public string pkdoc_no { get; set; }
        public int pkseq { get; set; }
        public System.DateTime pkdoc_date { get; set; }
        public short sign { get; set; }
        public decimal pkfx_rate { get; set; }
        public decimal paid { get; set; }
        public decimal fx_rate { get; set; }
        public decimal local_paid { get; set; }
        public decimal local_amount { get; set; }
        public decimal fx_gainloss { get; set; }
        public decimal v_gainloss { get; set; }
    }
}
