//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingProject2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class glstk
    {
        public string bsc_accno { get; set; }
        public string projcode { get; set; }
        public string deptcode { get; set; }
        public string plo_accno { get; set; }
        public string plc_accno { get; set; }
    }
}
