//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingProject2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gltax
    {
        public string taxcode { get; set; }
        public string taxdesp { get; set; }
        public decimal taxpec { get; set; }
        public string accno { get; set; }
        public string taxmethod { get; set; }
        public string taxtype { get; set; }
        public string taxgrp { get; set; }
        public string indcode { get; set; }
        public bool openacc { get; set; }
        public bool bothsp { get; set; }
        public bool nonclaim { get; set; }
        public bool @lock { get; set; }
        public bool pe_o1 { get; set; }
        public bool pe_o2 { get; set; }
        public bool inactive { get; set; }
    }
}
