//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingProject2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gltaxgrp
    {
        public string taxgrp { get; set; }
        public string taxgrp_desp { get; set; }
        public string taxsp { get; set; }
        public decimal taxgrp_pec { get; set; }
        public string taxgrp_type { get; set; }
        public string taxbox { get; set; }
        public byte taxseq { get; set; }
        public bool nonclaim { get; set; }
    }
}
