//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingProject2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gst_custom
    {
        public string doc_type { get; set; }
        public string doc_no { get; set; }
        public string accno { get; set; }
        public string custom_no { get; set; }
    }
}
