//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingProject2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gstau
    {
        public System.DateTime taxdate { get; set; }
        public bool amended { get; set; }
        public string taxno { get; set; }
        public string companyname { get; set; }
        public System.DateTime date_start { get; set; }
        public System.DateTime date_end { get; set; }
        public string doc_id { get; set; }
        public string abn { get; set; }
        public System.DateTime form_due { get; set; }
        public System.DateTime payment_due { get; set; }
        public string gst_method { get; set; }
        public string phone { get; set; }
        public string dc_name { get; set; }
        public System.DateTime dc_date { get; set; }
        public string taxperiod { get; set; }
        public byte gst_opt { get; set; }
        public decimal g1 { get; set; }
        public decimal g1_tax { get; set; }
        public byte g1_opt { get; set; }
        public decimal g2 { get; set; }
        public decimal g3 { get; set; }
        public decimal g10 { get; set; }
        public decimal g10_tax { get; set; }
        public decimal g11 { get; set; }
        public decimal g11_tax { get; set; }
        public decimal w1 { get; set; }
        public decimal w2 { get; set; }
        public decimal w3 { get; set; }
        public decimal w4 { get; set; }
        public decimal w5 { get; set; }
        public decimal sum_1a { get; set; }
        public decimal sum_4 { get; set; }
        public decimal sum_8a { get; set; }
        public decimal sum_1b { get; set; }
        public decimal sum_8b { get; set; }
        public decimal pay_9 { get; set; }
        public string createdby { get; set; }
        public string updatedby { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
        public Nullable<System.DateTime> lastupdate { get; set; }
    }
}
