//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingProject2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gstmy_pe
    {
        public System.DateTime pe_date { get; set; }
        public string type { get; set; }
        public System.DateTime fromdate { get; set; }
        public System.DateTime todate { get; set; }
        public System.DateTime taxyear { get; set; }
        public System.DateTime taxdate { get; set; }
        public System.DateTime date_adjust { get; set; }
        public string desp { get; set; }
        public bool amended { get; set; }
        public bool bf { get; set; }
        public decimal taxable_s { get; set; }
        public decimal exempt_s { get; set; }
        public decimal taxable { get; set; }
        public string dmr { get; set; }
        public decimal irr_o1 { get; set; }
        public decimal irr_o2 { get; set; }
        public decimal exempt_pct { get; set; }
        public decimal tax_re { get; set; }
        public decimal irr { get; set; }
        public decimal tax_recovered { get; set; }
        public decimal tax_es { get; set; }
        public decimal tax_adjust { get; set; }
        public bool adjusted { get; set; }
        public string doc_type { get; set; }
        public string doc_no { get; set; }
    }
}
