//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingProject2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gstsg
    {
        public System.DateTime taxdate { get; set; }
        public bool amended { get; set; }
        public string taxno { get; set; }
        public string companyname { get; set; }
        public System.DateTime date_start { get; set; }
        public System.DateTime date_end { get; set; }
        public decimal box1 { get; set; }
        public decimal box2 { get; set; }
        public decimal box3 { get; set; }
        public decimal box5 { get; set; }
        public decimal box6 { get; set; }
        public decimal box7 { get; set; }
        public decimal box9 { get; set; }
        public decimal box13 { get; set; }
        public string dc_name { get; set; }
        public System.DateTime dc_date { get; set; }
        public string createdby { get; set; }
        public string updatedby { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
        public Nullable<System.DateTime> lastupdate { get; set; }
    }
}
