//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingProject2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class paymode
    {
        public string paycode { get; set; }
        public string paydesp { get; set; }
        public string paytype { get; set; }
        public string accno { get; set; }
        public bool enter_num { get; set; }
        public string bkchg_accno { get; set; }
        public decimal bkchg_rate { get; set; }
        public decimal bkchg_min { get; set; }
        public decimal dispec1 { get; set; }
        public byte payseq { get; set; }
        public bool inactive { get; set; }
    }
}
