//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingProject2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class paytype
    {
        public string paytype1 { get; set; }
        public string typedesp { get; set; }
        public string realtype { get; set; }
        public byte seq { get; set; }
    }
}
