//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingProject2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pinv
    {
        public string doc_type { get; set; }
        public string doc_no { get; set; }
        public System.DateTime doc_date { get; set; }
        public string doc_desp { get; set; }
        public string doc_desp2 { get; set; }
        public byte doc_status { get; set; }
        public int doc_set { get; set; }
        public string refno { get; set; }
        public string refno2 { get; set; }
        public string suppcode { get; set; }
        public string name { get; set; }
        public string attn2 { get; set; }
        public short terms { get; set; }
        public string accmgr_id { get; set; }
        public string curr_code { get; set; }
        public decimal fx_rate { get; set; }
        public decimal discount1 { get; set; }
        public decimal discount2 { get; set; }
        public decimal discount { get; set; }
        public decimal dispec1 { get; set; }
        public decimal dispec2 { get; set; }
        public decimal tax1 { get; set; }
        public decimal tax2 { get; set; }
        public decimal taxadj { get; set; }
        public decimal tax { get; set; }
        public decimal taxpec1 { get; set; }
        public decimal taxpec2 { get; set; }
        public string taxcode { get; set; }
        public decimal taxable { get; set; }
        public decimal rndoff { get; set; }
        public decimal subtotal { get; set; }
        public decimal nett { get; set; }
        public decimal total { get; set; }
        public decimal local_gross { get; set; }
        public decimal local_discount { get; set; }
        public decimal local_nett { get; set; }
        public decimal local_tax { get; set; }
        public decimal local_rndoff { get; set; }
        public decimal local_total { get; set; }
        public decimal local_totalrp { get; set; }
        public decimal mc1 { get; set; }
        public decimal local_mc1 { get; set; }
        public decimal deposit { get; set; }
        public short sign { get; set; }
        public short signqty { get; set; }
        public string batchno { get; set; }
        public string projcode { get; set; }
        public string deptcode { get; set; }
        public string shipmethod { get; set; }
        public string hremark1 { get; set; }
        public string hremark2 { get; set; }
        public string hremark3 { get; set; }
        public string hremark4 { get; set; }
        public string hremark5 { get; set; }
        public string hremark6 { get; set; }
        public string hremark7 { get; set; }
        public string hremark8 { get; set; }
        public string hremark9 { get; set; }
        public string hremark10 { get; set; }
        public string hremark11 { get; set; }
        public string hremark12 { get; set; }
        public string hremark13 { get; set; }
        public string hremark14 { get; set; }
        public string hremark15 { get; set; }
        public string remark1 { get; set; }
        public string po_no { get; set; }
        public string grn_no { get; set; }
        public string accno1 { get; set; }
        public string accno1_ref { get; set; }
        public decimal accno1_amt { get; set; }
        public bool postgl { get; set; }
        public bool poststk { get; set; }
        public bool @void { get; set; }
        public System.DateTime void_date { get; set; }
        public bool exported { get; set; }
        public bool selfbilled { get; set; }
        public string cpdoc_type { get; set; }
        public string cpdoc_no { get; set; }
        public int printcnt { get; set; }
        public string approvedby { get; set; }
        public System.DateTime approveddate { get; set; }
        public System.DateTime tsdate { get; set; }
        public string createdby { get; set; }
        public string updatedby { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
        public Nullable<System.DateTime> lastupdate { get; set; }
    }
}
