//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingProject2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class prodbom
    {
        public string prodcode { get; set; }
        public int bom_no { get; set; }
        public string bom_prodcode { get; set; }
        public int bom_no_sf { get; set; }
        public string bom_location { get; set; }
        public decimal bom_qty { get; set; }
        public bool bom_print { get; set; }
        public int bom_seq { get; set; }
    }
}
