//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingProject2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class prodhprice
    {
        public string prodcode { get; set; }
        public string accno { get; set; }
        public string doc_type1 { get; set; }
        public string doc_no1 { get; set; }
        public System.DateTime doc_date1 { get; set; }
        public decimal price1 { get; set; }
        public string unit1 { get; set; }
        public string doc_type2 { get; set; }
        public string doc_no2 { get; set; }
        public System.DateTime doc_date2 { get; set; }
        public decimal price2 { get; set; }
        public string unit2 { get; set; }
        public string doc_type3 { get; set; }
        public string doc_no3 { get; set; }
        public System.DateTime doc_date3 { get; set; }
        public decimal price3 { get; set; }
        public string unit3 { get; set; }
        public string doc_type4 { get; set; }
        public string doc_no4 { get; set; }
        public System.DateTime doc_date4 { get; set; }
        public decimal price4 { get; set; }
        public string unit4 { get; set; }
        public string doc_type5 { get; set; }
        public string doc_no5 { get; set; }
        public System.DateTime doc_date5 { get; set; }
        public decimal price5 { get; set; }
        public string unit5 { get; set; }
    }
}
