//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingProject2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class prodsn
    {
        public string prodcode { get; set; }
        public string serialno { get; set; }
        public decimal qty { get; set; }
        public string initlocation { get; set; }
        public string location { get; set; }
        public string remark1 { get; set; }
        public string remark2 { get; set; }
        public string doc_type { get; set; }
        public string doc_no { get; set; }
        public int line_no { get; set; }
        public System.DateTime doc_date { get; set; }
    }
}
