//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingProject2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class prodext
    {
        public string prodcode { get; set; }
        public string remark1 { get; set; }
        public string remark2 { get; set; }
        public string remark3 { get; set; }
        public string remark4 { get; set; }
        public string remark5 { get; set; }
        public string remark6 { get; set; }
        public string remark7 { get; set; }
        public string remark8 { get; set; }
        public string remark9 { get; set; }
        public string remark10 { get; set; }
        public string remarks { get; set; }
        public bool fmlqty { get; set; }
        public bool fmlprice { get; set; }
        public decimal fmlqty1 { get; set; }
        public decimal fmlqty2 { get; set; }
        public decimal fmlqty3 { get; set; }
        public decimal fmlqty4 { get; set; }
        public decimal fmlqty5 { get; set; }
        public decimal fmlqty6 { get; set; }
        public decimal fmlqty7 { get; set; }
        public decimal fmlval1 { get; set; }
        public decimal fmlval2 { get; set; }
        public decimal fmlval3 { get; set; }
        public decimal pg1disp1 { get; set; }
        public decimal pg1disp2 { get; set; }
        public decimal pg2disp1 { get; set; }
        public decimal pg2disp2 { get; set; }
        public decimal pg3disp1 { get; set; }
        public decimal pg3disp2 { get; set; }
        public decimal pg4disp1 { get; set; }
        public decimal pg4disp2 { get; set; }
        public decimal pg5disp1 { get; set; }
        public decimal pg5disp2 { get; set; }
        public System.DateTime pm_fromdate { get; set; }
        public System.DateTime pm_todate { get; set; }
        public decimal pm_price { get; set; }
        public decimal pm_disp1 { get; set; }
        public decimal pm_disp2 { get; set; }
        public decimal pm_member_disp { get; set; }
        public bool fmeter { get; set; }
        public decimal curr_meter { get; set; }
    }
}
