//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingProject2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class prodrprice
    {
        public string prodcode { get; set; }
        public string accno { get; set; }
        public short sign { get; set; }
        public string unit { get; set; }
        public decimal price { get; set; }
        public decimal disp1 { get; set; }
        public decimal disp2 { get; set; }
        public decimal disp3 { get; set; }
        public string sku { get; set; }
    }
}
