//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingProject2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class prodgrp
    {
        public string pgrpcode { get; set; }
        public string pgrpdesp { get; set; }
        public string taxcode_p { get; set; }
        public string taxcode_s { get; set; }
        public string p_accno { get; set; }
        public string cp_accno { get; set; }
        public string pret_accno { get; set; }
        public string s_accno { get; set; }
        public string cs_accno { get; set; }
        public string sret_accno { get; set; }
        public string bsc_accno { get; set; }
        public string plo_accno { get; set; }
        public string plc_accno { get; set; }
        public bool auto { get; set; }
        public string prefix { get; set; }
        public decimal curr_no { get; set; }
        public byte no_width { get; set; }
    }
}
