//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingProject2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class produom
    {
        public string prodcode { get; set; }
        public string uom_code { get; set; }
        public decimal uom_rate { get; set; }
        public decimal b_unitq { get; set; }
        public decimal s_unitq { get; set; }
        public decimal ucost { get; set; }
        public decimal price { get; set; }
        public byte seq { get; set; }
        public string barcode { get; set; }
    }
}
