//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingProject2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public string prodcode { get; set; }
        public string proddesp { get; set; }
        public string proddesp2 { get; set; }
        public string pgrpcode { get; set; }
        public string psgrpcode { get; set; }
        public string brand { get; set; }
        public string shelf { get; set; }
        public string ptype { get; set; }
        public string costing { get; set; }
        public string costcode { get; set; }
        public string barcode { get; set; }
        public string unit { get; set; }
        public decimal ucost { get; set; }
        public decimal utd_cost { get; set; }
        public decimal minprice { get; set; }
        public decimal price1 { get; set; }
        public decimal price2 { get; set; }
        public decimal price3 { get; set; }
        public decimal price4 { get; set; }
        public decimal price5 { get; set; }
        public decimal markup { get; set; }
        public decimal minqty { get; set; }
        public decimal maxqty { get; set; }
        public decimal reorder { get; set; }
        public decimal qtybal { get; set; }
        public string taxcode_p { get; set; }
        public string taxcode_s { get; set; }
        public string p_accno { get; set; }
        public string cp_accno { get; set; }
        public string pret_accno { get; set; }
        public string s_accno { get; set; }
        public string cs_accno { get; set; }
        public string sret_accno { get; set; }
        public string bsc_accno { get; set; }
        public string plo_accno { get; set; }
        public string plc_accno { get; set; }
        public bool batch_flag { get; set; }
        public bool sn_flag { get; set; }
        public bool bom_flag { get; set; }
        public decimal bom_mcost { get; set; }
        public bool promoter { get; set; }
        public bool editdesp { get; set; }
        public bool editprice { get; set; }
        public string prodpict { get; set; }
        public bool favourite { get; set; }
        public bool inactive { get; set; }
        public string createdby { get; set; }
        public string updatedby { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
        public Nullable<System.DateTime> lastupdate { get; set; }
    }
}
