//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingProject2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class project
    {
        public string projcode { get; set; }
        public string projdesp { get; set; }
        public string projdesp2 { get; set; }
        public decimal complete { get; set; }
        public System.DateTime date_start { get; set; }
        public System.DateTime date_end { get; set; }
        public decimal contractsum { get; set; }
        public bool retain_bf { get; set; }
        public byte seq { get; set; }
        public string acode1 { get; set; }
        public string acode2 { get; set; }
        public string acode3 { get; set; }
        public string acode4 { get; set; }
        public string acode5 { get; set; }
        public bool inactive { get; set; }
    }
}
