//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingProject2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class revaluedet
    {
        public string doc_type { get; set; }
        public string doc_no { get; set; }
        public short sign { get; set; }
        public string classify { get; set; }
        public string rv_accno { get; set; }
        public string rv_doc_type { get; set; }
        public string rv_doc_no { get; set; }
        public int rv_seq { get; set; }
        public string rv_refno { get; set; }
        public string rv_billtype { get; set; }
        public string curr_code { get; set; }
        public decimal fx_rate { get; set; }
        public decimal rv_rate { get; set; }
        public decimal fx_amount { get; set; }
        public decimal amount { get; set; }
        public decimal fx_gainloss { get; set; }
    }
}
