//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingProject2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sdodet
    {
        public int dkey { get; set; }
        public string doc_type { get; set; }
        public string doc_no { get; set; }
        public int line_no { get; set; }
        public string prodcode { get; set; }
        public string desp { get; set; }
        public string desp2 { get; set; }
        public string unit { get; set; }
        public decimal uom_rate { get; set; }
        public decimal qty { get; set; }
        public decimal qtyrp { get; set; }
        public decimal qtywo { get; set; }
        public decimal price { get; set; }
        public decimal disamt1 { get; set; }
        public decimal disamt2 { get; set; }
        public decimal disamt3 { get; set; }
        public decimal disamt { get; set; }
        public decimal disp1 { get; set; }
        public decimal disp2 { get; set; }
        public decimal disp3 { get; set; }
        public decimal taxamt1 { get; set; }
        public decimal taxamtadj1 { get; set; }
        public decimal taxamt { get; set; }
        public decimal taxp1 { get; set; }
        public decimal gross_amt { get; set; }
        public decimal nett_amt { get; set; }
        public decimal amt { get; set; }
        public decimal local_price { get; set; }
        public decimal local_gamt { get; set; }
        public decimal local_disamt { get; set; }
        public decimal local_namt { get; set; }
        public decimal local_taxamt1 { get; set; }
        public decimal local_taxamtadj1 { get; set; }
        public decimal local_taxamt { get; set; }
        public decimal local_amt { get; set; }
        public decimal local_amtrp { get; set; }
        public decimal mcamt1 { get; set; }
        public decimal local_mcamt1 { get; set; }
        public bool foc { get; set; }
        public decimal weight { get; set; }
        public decimal fmlqty1 { get; set; }
        public decimal fmlqty2 { get; set; }
        public decimal fmlqty3 { get; set; }
        public decimal fmlqty4 { get; set; }
        public decimal fmlqty5 { get; set; }
        public decimal fmlqty6 { get; set; }
        public decimal fmlqty7 { get; set; }
        public decimal fmluqty { get; set; }
        public decimal fmlval1 { get; set; }
        public decimal fmlval2 { get; set; }
        public decimal fmlval3 { get; set; }
        public string taxcode { get; set; }
        public string location { get; set; }
        public string batchcode { get; set; }
        public string accno { get; set; }
        public string projcode { get; set; }
        public string deptcode { get; set; }
        public decimal utd_cost { get; set; }
        public bool sum_up { get; set; }
        public byte grouptoline { get; set; }
        public string bremark1 { get; set; }
        public string bremark2 { get; set; }
        public string bremark3 { get; set; }
        public string bremark4 { get; set; }
        public string bremark5 { get; set; }
        public string bremark6 { get; set; }
        public string bremark7 { get; set; }
        public string bremark8 { get; set; }
        public string bremark9 { get; set; }
        public string bremark10 { get; set; }
        public string bremarks { get; set; }
        public string pkdoc_type { get; set; }
        public string pkdoc_no { get; set; }
        public int pkdkey { get; set; }
    }
}
