//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingProject2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sinvpay
    {
        public string doc_type { get; set; }
        public string doc_no { get; set; }
        public string paycode { get; set; }
        public string curr_code { get; set; }
        public decimal fx_rate { get; set; }
        public string accno { get; set; }
        public string payrefno { get; set; }
        public decimal payamt { get; set; }
        public decimal paid { get; set; }
        public decimal changed { get; set; }
        public string appcode { get; set; }
        public string bkchg_accno { get; set; }
        public decimal bkchg_amt { get; set; }
        public decimal repay { get; set; }
        public System.DateTime repay_date { get; set; }
    }
}
