//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingProject2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class stkt
    {
        public string doc_type { get; set; }
        public string doc_no { get; set; }
        public System.DateTime doc_date { get; set; }
        public string doc_desp { get; set; }
        public string doc_desp2 { get; set; }
        public string projcode { get; set; }
        public string deptcode { get; set; }
        public string from_loc { get; set; }
        public string to_loc { get; set; }
        public string source { get; set; }
        public string hremark1 { get; set; }
        public string hremark2 { get; set; }
        public string createdby { get; set; }
        public string updatedby { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
        public Nullable<System.DateTime> lastupdate { get; set; }
    }
}
