//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingProject2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class stktsdet
    {
        public int dkey { get; set; }
        public string doc_type { get; set; }
        public string doc_no { get; set; }
        public int line_no { get; set; }
        public string prodcode { get; set; }
        public string desp { get; set; }
        public string desp2 { get; set; }
        public string unit { get; set; }
        public decimal uom_rate { get; set; }
        public decimal qty { get; set; }
        public decimal price { get; set; }
        public decimal amt { get; set; }
        public decimal bom_mcost { get; set; }
        public int bom_no { get; set; }
        public bool bom_mlevel { get; set; }
        public string location { get; set; }
        public string batchcode { get; set; }
        public string to_prodcode { get; set; }
        public string bremark1 { get; set; }
        public string bremark2 { get; set; }
        public string bremark3 { get; set; }
        public string bremarks { get; set; }
    }
}
