//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingProject2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class supervisor
    {
        public string supervisor_id { get; set; }
        public string supervisor_name { get; set; }
        public string supervisor_pwd { get; set; }
        public bool inactive { get; set; }
    }
}
