//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingProject2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class supplier
    {
        public string suppcode { get; set; }
        public string name { get; set; }
        public string name2 { get; set; }
        public string addr { get; set; }
        public string area { get; set; }
        public string phone1 { get; set; }
        public string phone2 { get; set; }
        public string fax { get; set; }
        public string email { get; set; }
        public string website { get; set; }
        public string attn { get; set; }
        public string contact { get; set; }
        public short terms { get; set; }
        public decimal crlimit { get; set; }
        public string accno { get; set; }
        public string curr_code { get; set; }
        public string suppgrp { get; set; }
        public string accmgr_id { get; set; }
        public string business { get; set; }
        public string bankaccno { get; set; }
        public string regno { get; set; }
        public string taxno { get; set; }
        public string taxcode { get; set; }
        public bool oversea { get; set; }
        public bool notax { get; set; }
        public string appno { get; set; }
        public bool inactive { get; set; }
        public byte pricegrp { get; set; }
        public string mremark1 { get; set; }
        public string mremark2 { get; set; }
        public string mremark3 { get; set; }
        public string mremark4 { get; set; }
        public string mremark5 { get; set; }
        public string mremarks { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
        public Nullable<System.DateTime> lastupdate { get; set; }
    }
}
