//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingProject2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tax
    {
        public string accno { get; set; }
        public string doc_type { get; set; }
        public string doc_no { get; set; }
        public int seq { get; set; }
        public System.DateTime doc_date { get; set; }
        public string refno { get; set; }
        public string refno2 { get; set; }
        public string desp { get; set; }
        public string desp2 { get; set; }
        public string taxcode { get; set; }
        public decimal taxable { get; set; }
        public decimal tax1 { get; set; }
        public System.DateTime taxdate { get; set; }
        public string bill_doc_type { get; set; }
        public string bill_doc_no { get; set; }
        public int bill_seq { get; set; }
        public string adj_doc_type { get; set; }
        public string adj_doc_no { get; set; }
        public int adj_seq { get; set; }
        public string pay_doc_type { get; set; }
        public string pay_doc_no { get; set; }
        public int pay_seq { get; set; }
    }
}
