//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingProject2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class udrptorder
    {
        public int mkey { get; set; }
        public short seq { get; set; }
        public string flddesp { get; set; }
        public string fldexpr { get; set; }
    }
}
