//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingProject2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class udrpt
    {
        public int mkey { get; set; }
        public string moduleid { get; set; }
        public string desp { get; set; }
        public string reportfile { get; set; }
        public string sqlcmd { get; set; }
        public string editor { get; set; }
        public System.DateTime createdate { get; set; }
        public System.DateTime lastupdate { get; set; }
    }
}
