//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingProject2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class udrptfilter
    {
        public int mkey { get; set; }
        public short seq { get; set; }
        public string flddesp { get; set; }
        public string fldtype { get; set; }
        public string fromvar { get; set; }
        public string tovar { get; set; }
        public string fromstr { get; set; }
        public string tostr { get; set; }
        public System.DateTime fromdate { get; set; }
        public System.DateTime todate { get; set; }
        public decimal fromvalue { get; set; }
        public decimal tovalue { get; set; }
        public bool bitvalue { get; set; }
    }
}
