//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingProject2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usergrp
    {
        public string grpid { get; set; }
        public string grpdesp { get; set; }
        public bool menu_gl { get; set; }
        public bool menu_cb { get; set; }
        public bool menu_ar { get; set; }
        public bool menu_ap { get; set; }
        public bool menu_stock { get; set; }
        public bool menu_sales { get; set; }
        public bool menu_purchase { get; set; }
        public bool menu_pos { get; set; }
        public bool menu_pos_ts { get; set; }
        public bool menu_tax { get; set; }
        public bool menu_system { get; set; }
    }
}
