//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingProject2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public string user_id { get; set; }
        public string username { get; set; }
        public string userpwd { get; set; }
        public string grpid { get; set; }
        public byte access_mode { get; set; }
        public string email { get; set; }
        public string smtp_server { get; set; }
        public int smtp_serverport { get; set; }
        public bool smtp_usessl { get; set; }
        public string projcode { get; set; }
        public string deptcode { get; set; }
        public string location { get; set; }
    }
}
